spring:
  application:
    name: service_practice
  main:
    allow-bean-definition-overriding: true


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://zeus.code.cn:20800/eureka/
  instance:
    prefer-ip-address: true
    hostname: zeus.code.cn

server:
  port: 8080


